export const mockCustomers = [
  {
    id: '1',
    name: 'สมชาย ใจดี',
    phone: '0812345678',
    email: 'somchai@example.com',
    segment: 'VIP',
    lastInteraction: '2025-11-28',
    totalSpent: 15000,
    status: 'active',
  },
  {
    id: '2',
    name: 'วิภา สุขสันต์',
    phone: '0823456789',
    email: 'wipa@example.com',
    segment: 'Regular',
    lastInteraction: '2025-11-27',
    totalSpent: 5000,
    status: 'active',
  },
  {
    id: '3',
    name: 'ประยุทธ์ มั่นคง',
    phone: '0834567890',
    email: 'prayut@example.com',
    segment: 'New',
    lastInteraction: '2025-11-26',
    totalSpent: 1200,
    status: 'active',
  },
  {
    id: '4',
    name: 'สุภาพร ยิ้มแย้ม',
    phone: '0845678901',
    email: 'supaporn@example.com',
    segment: 'VIP',
    lastInteraction: '2025-11-25',
    totalSpent: 22000,
    status: 'active',
  },
  {
    id: '5',
    name: 'อนุชา รักษ์ดี',
    phone: '0856789012',
    email: 'anucha@example.com',
    segment: 'Regular',
    lastInteraction: '2025-11-20',
    totalSpent: 3500,
    status: 'inactive',
  },
];

export const mockAnalytics = {
  totalFollowers: 12547,
  messagesSent: 8923,
  clickRate: 28.5,
  revenue: 245678,
  followersTrend: [
    { month: 'ม.ค.', value: 8500 },
    { month: 'ก.พ.', value: 9200 },
    { month: 'มี.ค.', value: 9800 },
    { month: 'เม.ย.', value: 10500 },
    { month: 'พ.ค.', value: 11200 },
    { month: 'มิ.ย.', value: 12547 },
  ],
  messagesByType: [
    { type: 'ข้อความส่วนตัว', count: 4523 },
    { type: 'แบรอดแคสต์', count: 2800 },
    { type: 'แชทบอท', count: 1600 },
  ],
  engagementByDay: [
    { day: 'จ', rate: 25 },
    { day: 'อ', rate: 28 },
    { day: 'พ', rate: 32 },
    { day: 'พฤ', rate: 30 },
    { day: 'ศ', rate: 35 },
    { day: 'ส', rate: 42 },
    { day: 'อา', rate: 38 },
  ],
};

export const mockBroadcasts = [
  {
    id: '1',
    name: 'โปรโมชั่นสิ้นเดือน',
    status: 'sent',
    sentAt: '2025-11-28',
    recipients: 12547,
    opened: 8921,
    clicked: 2845,
  },
  {
    id: '2',
    name: 'ข่าวสารสินค้าใหม่',
    status: 'scheduled',
    scheduledAt: '2025-11-30',
    recipients: 12547,
    opened: 0,
    clicked: 0,
  },
  {
    id: '3',
    name: 'คูปองพิเศษวันเกิด',
    status: 'draft',
    recipients: 0,
    opened: 0,
    clicked: 0,
  },
];

export const mockAIGeneratedMessages = [
  {
    id: '1',
    variant: 'A',
    content: '🎉 โปรโมชั่นพิเศษ! ลดสูงสุด 50% สำหรับสมาชิกทุกท่าน\nรับส่วนลดเพิ่มอีก 10% เมื่อซื้อครบ 1,000 บาท\n✨ เฉพาะวันนี้ - 30 พ.ย. นี้เท่านั้น!\nคลิกเลย 👉 [ลิงก์]',
  },
  {
    id: '2',
    variant: 'B',
    content: '💝 สมาชิกพิเศษที่รัก!\nส่งท้ายเดือนพฤศจิกายนด้วยโปรโมชั่นสุดพิเศษ\n📦 ลด 50% + ส่วนลดเพิ่ม 10% เมื่อช้อปครบ 1,000฿\nของดีรออยู่ ช้อปเลย! [ลิงก์]',
  },
  {
    id: '3',
    variant: 'C',
    content: 'ช้อปสุดคุ้มส่งท้ายเดือน! 🛍️\n✅ ลด 50% ทุกรายการ\n✅ รับคูปองเพิ่ม 10% (ช้อปครบ 1,000฿)\n⏰ เหลือเวลาจำกัด ถึง 30 พ.ย. นี้!\nช้อปเลย 👉 [ลิงก์]',
  },
];

export const tierFeatures = {
  starter: {
    name: 'Starter',
    price: 0,
    features: [
      'ผู้ติดตามสูงสุด 1,000 คน',
      'แบรอดแคสต์ 500 ข้อความ/เดือน',
      'รายงานพื้นฐาน',
      'ตอบกลับอัตโนมัติ',
    ],
    limits: {
      maxFollowers: 1000,
      monthlyBroadcasts: 500,
      aiGeneration: 10,
      abTests: 0,
      support: 'email',
    },
  },
  growth: {
    name: 'Growth',
    price: 1990,
    features: [
      'ผู้ติดตามสูงสุด 10,000 คน',
      'แบรอดแคสต์ไม่จำกัด',
      'รายงานขั้นสูง + Analytics',
      'AI สร้างข้อความ 100 ครั้ง/เดือน',
      'A/B Testing',
      'แท็กลูกค้าอัตโนมัติ',
      'Support แชทสด',
    ],
    limits: {
      maxFollowers: 10000,
      monthlyBroadcasts: Infinity,
      aiGeneration: 100,
      abTests: 5,
      support: 'chat',
    },
  },
  enterprise: {
    name: 'Enterprise',
    price: 4990,
    features: [
      'ผู้ติดตามไม่จำกัด',
      'แบรอดแคสต์ไม่จำกัด',
      'รายงาน + Analytics แบบ Real-time',
      'AI สร้างข้อความไม่จำกัด',
      'A/B Testing ไม่จำกัด',
      'API Access',
      'Custom Integration',
      'Dedicated Account Manager',
      'Support 24/7',
    ],
    limits: {
      maxFollowers: Infinity,
      monthlyBroadcasts: Infinity,
      aiGeneration: Infinity,
      abTests: Infinity,
      support: '24/7',
    },
  },
};
